version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my-apollo-api
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    container_name: my-react-client
    ports:
      - "3000:3000"  # Vite dev server port
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    command: ["npm", "run", "dev"]
